# Endeffector
endeffector:  
  a_val: 0.05
  b_val: 0.05
  c_val: 0.1
  eps1_val: 1.0
  eps2_val: 1.0

# Attractive Goal 
goal:
  a_val: 0.05
  b_val: 0.05
  c_val: 0.1
  eps1_val: 1.0
  eps2_val: 1.0
  c0: 0.1
  kappa_FT: [10.0, 10.0]
  
# Obstacles
obstacle_1:
  a_val: 0.1
  b_val: 0.08
  c_val: 0.07
  eps1_val: 0.5
  eps2_val: 0.1
  x_val: 0.45
  y_val: 0.05
  z_val: 0.25
  qw_val: 0.7071
  qx_val: 0.5
  qy_val: 0.2
  qz_val: -0.3
  lambda_FT: [50.0, 3000.0]
  beta_val: 1.0
  eta_val: 1.0
  
obstacle_2:
  a_val: 0.05
  b_val: 0.1
  c_val: 0.08
  eps1_val: 1.0
  eps2_val: 0.1
  x_val: 0.6
  y_val: -0.1
  z_val: 0.7
  qw_val: 0.6
  qx_val: -0.2
  qy_val: 0.9
  qz_val: 0.5
  lambda_FT: [20.0, 700.0]
  beta_val: 1.0
  eta_val: 2.0
  
obstacle_3:
  a_val: 0.05
  b_val: 0.1
  c_val: 0.08
  eps1_val: 1.0
  eps2_val: 0.5
  x_val: 0.8
  y_val: 0.0
  z_val: 0.7
  qw_val: 0.8
  qx_val: 0.1
  qy_val: -0.4
  qz_val: 0.2
  lambda_FT: [10.0, 200.0]
  beta_val: 2.0
  eta_val: 2.0
  
workspace_1:
  a_val: 0.6
  b_val: 0.5
  c_val: 0.5
  eps1_val: 0.1
  eps2_val: 0.1
  x_val: 0.7
  y_val: 0.0
  z_val: 0.6
  qw_val: 1.0
  qx_val: 0.0
  qy_val: 0.0
  qz_val: 0.0
  lambda_FT: [5.0, 1.0]
  beta_val: 1.0
  eta_val: 1.0

# CDMPs Parameters
cdmp:
  alpha_s:      7.0
  k_gain:     500.0
  rbfs_pSec:    4.0
  tau_scaler:   1.0
  max_steps: 5000.0
  tolerance:    0.001
  
# Animation Parameters
animation:
  sample_interval: 20 # selects every sample_interval's frame
  time_scaler: 1.0 # animation speed relative to realtime
  view_angles: [0.0, -90.0, 0.0]
  xlim3d: [0.1, 1.3]
  ylim3d: [-0.5, 0.5]
  zlim3d: [0.1, 1.1]
  save: null # null if you don't want to save. 1 otherwise
  plot: 1 # null if you don't want to plot. 1 otherwise

